apiVersion: config.openshift.io/v1
kind: DNS
metadata:
  creationTimestamp: null
  name: cluster
spec:
  baseDomain: dev.ocp-example.com
  privateZone:
    tags:
      Name: dev-k7jhm-int
      kubernetes.io/cluster/dev-k7jhm: owned
status: {}
