apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-metric-serving-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDJjCCAg6gAwIBAgIIQAdWqI77YHYwDQYJKoZIhvcNAQELBQAwMTESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRswGQYDVQQDExJldGNkLW1ldHJpYy1zaWduZXIwHhcNMjEw
    MjAyMTc0OTQyWhcNMzEwMTMxMTc0OTQyWjAxMRIwEAYDVQQLEwlvcGVuc2hpZnQx
    GzAZBgNVBAMTEmV0Y2QtbWV0cmljLXNpZ25lcjCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBANZ6CT3+BIJ1TkmWh9t0Zi7p3WbrYhtGGmVtf5oGEoqpskFQ
    GE1/lHidZN2C13UXCfCF9Mnd40QyS59LVnjJSkbTooccPsbcxz/SJqFxBqGFDeOy
    USTdwv2eGHNaA7qAZq05SvsD8r/3xVet5DrAgccGYoPOZbtHaSOJuCt8CkoRG90a
    E4ZCn80H7usby3jhpJ8IRtrUocSHCMFgWvNLtk2TJsKJUcAWrUgwRA0zX0N8HSrN
    QYDy2Cd2k+t/VCHHv/x4iOOLPuxtuLpBB/d4FmV5XYzfplSIFMLN6bsX30bXZaqd
    2nP1h2sI5mi2c8mhJ+/RVVtWCZyyVRRfYxFBf+0CAwEAAaNCMEAwDgYDVR0PAQH/
    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLA//FN4bMN7tDwpOZys
    ZAks7lEtMA0GCSqGSIb3DQEBCwUAA4IBAQCtHQmjPeSF82l1xm850qQHs1Hdb9Z9
    oX1K5H04dUGitfWCn7/ZTA8luNLdbxdRNCbfqOogDrEMQm1jIPjQiNn2yBUi6rzj
    b1KOeujMY06Sut7lCmSVrhCeFsYM7XRmMN2ZvsNpQWf4zGo+6DS0rZpna79nb25e
    JLgG83OP8c3heaWYzMyVtnskzR8BRzmjfIV2Eg9WfgYW0JGFIfV17rKxjryGwR4Y
    nz9qvSHrjDe26F+1miNBSzAxZAgBWYCl4RxycE5cU6yViojTgNb9b/Cy5PNAHzC+
    ggKr6eAedZPM2Gstttw14MNuAoaUXZJYJMLScH2dRRZMxYrpFnFw7vtw
    -----END CERTIFICATE-----
    
